FROM ubuntu:22.04

# shell 格式 (CMD command param)：如果你需要命令在一个 shell 环境中运行（例如，你需要使用 shell 的环境变量或者 shell 的管道、重定向等特性），那么你应该使用这种格式。
CMD sleep 5
# exec 格式 (CMD ["command", "param"])：直接被操作系统执行。这种格式更安全，因为它不会受到 shell 注入攻击的影响。
# CMD ["sleep", 5]
