Vagrant.configure("2") do |config|
  config.vm.define "vm1" do |vm1|
    vm1.vm.box = "ubuntu/jammy64"

    vm1.vm.synced_folder ".", "/vagrant_data"

    vm1.vm.provision "shell", path: "bootstrap.sh"

    # Default user is "vagrant", password is "vagrant"
    config.vm.provision "shell", inline: <<-SHELL
      echo -e "root\nroot" | sudo passwd root
    SHELL
  end
end
