CREATE DATABASE IF NOT EXISTS demo;

USE demo;

CREATE TABLE IF NOT EXISTS dummy (
  id INT AUTO_INCREMENT PRIMARY KEY,
  data VARCHAR(255)
);

DELIMITER $$
CREATE PROCEDURE InsertRandomData()
BEGIN
  DECLARE i INT DEFAULT 0;
  WHILE i < 10 DO
    INSERT INTO dummy (data)
    VALUES (LPAD(FLOOR(RAND() * 1000000000), 10, '0'));
    SET i = i + 1;
  END WHILE;
END $$
DELIMITER ;

CALL InsertRandomData();

DROP PROCEDURE IF EXISTS InsertRandomData;
